//
//  Outline.swift
//  
//
//  Created by Maurice Parker on 11/6/20.
//

import Foundation

public extension Notification.Name {
	static let OutlineBodyDidChange = Notification.Name(rawValue: "OutlineBodyDidChange")
}

public final class Outline: RowContainer, Identifiable, Equatable, Codable {
	
	public var id: EntityID
	public var title: String? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var created: Date? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var updated: Date? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var ownerName: String? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var ownerEmail: String? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var ownerURL: String? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var verticleScrollState: Int? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var isFavorite: Bool? {
		didSet {
			documentMetaDataDidChange()
		}
	}
	
	public var isFiltered: Bool? {
		didSet {
			documentMetaDataDidChange()
		}
	}

	public var rows: [TextRow]? {
		didSet {
			rowDictionaryNeedUpdate = true
		}
	}
	
	public var shadowTable: [TextRow]?
	
	public var isEmpty: Bool {
		return (title == nil || title?.isEmpty ?? true) && (rows == nil || rows?.isEmpty ?? true)
	}
	
	public var account: Account? {
		return AccountManager.shared.findAccount(accountID: id.accountID)
	}
	
	public var folder: Folder? {
		let folderID = EntityID.folder(id.accountID, id.folderUUID)
		return AccountManager.shared.findFolder(folderID)
	}

	public var expansionState: String {
		get {
			var currentRow = 0
			var expandedRows = [String]()
			
			func expandedRowVisitor(_ visited: TextRow) {
				if visited.isExpanded ?? true {
					expandedRows.append(String(currentRow))
				}
				currentRow = currentRow + 1
				visited.rows?.forEach { $0.visit(visitor: expandedRowVisitor) }
			}

			rows?.forEach { $0.visit(visitor: expandedRowVisitor(_:)) }
			
			return expandedRows.joined(separator: ",")
		}
		set {
			let expandedRows = newValue.split(separator: ",")
				.map({ String($0).trimmingWhitespace })
				.filter({ !$0.isEmpty })
				.compactMap({ Int($0) })
			
			var currentRow = 0
			
			func expandedRowVisitor(_ visited: TextRow) {
				visited.isExpanded = expandedRows.contains(currentRow)
				currentRow = currentRow + 1
				visited.rows?.forEach { $0.visit(visitor: expandedRowVisitor) }
			}

			rows?.forEach { $0.visit(visitor: expandedRowVisitor(_:)) }
		}
	}
	
	public var cursorCoordinates: CursorCoordinates? {
		get {
			guard let rowID = cursorRowID,
				  let row = findRow(id: rowID),
				  let isInNotes = cursorIsInNotes,
				  let position = cursorPosition else {
				return nil
			}
			return CursorCoordinates(row: row, isInNotes: isInNotes, cursorPosition: position)
		}
		set {
			cursorRowID = newValue?.row.id
			cursorIsInNotes = newValue?.isInNotes
			cursorPosition = newValue?.cursorPosition
			documentMetaDataDidChange()
		}
	}
	
	enum CodingKeys: String, CodingKey {
		case id = "id"
		case title = "title"
		case created = "created"
		case updated = "updated"
		case ownerName = "ownerName"
		case ownerEmail = "ownerEmail"
		case ownerURL = "ownerURL"
		case verticleScrollState = "verticleScrollState"
		case isFavorite = "isFavorite"
		case isFiltered = "isFiltered"
		case cursorRowID = "cursorRowID"
		case cursorIsInNotes = "cursorIsInNotes"
		case cursorPosition = "cursorPosition"
	}

	private var cursorRowID: String?
	private var cursorIsInNotes: Bool?
	private var cursorPosition: Int?
	
	private var rowsFile: RowsFile?
	
	private var rowDictionaryNeedUpdate = true
	private var _idToRowDictionary = [String: TextRow]()
	private var idToRowDictionary: [String: TextRow] {
		if rowDictionaryNeedUpdate {
			rebuildHeadlineDictionary()
		}
		return _idToRowDictionary
	}
	
	init(parentID: EntityID, title: String?) {
		self.id = EntityID.document(parentID.accountID, parentID.folderUUID, UUID().uuidString)
		self.title = title
		self.created = Date()
		self.updated = Date()
		rowsFile = RowsFile(outline: self)
	}

	public func findRow(id: String) -> TextRow? {
		return idToRowDictionary[id]
	}
	
	public func markdown(indentLevel: Int = 0) -> String {
		var returnToSuspend = false
		if rows == nil {
			returnToSuspend = true
			load()
		}
		
		var md = "# \(title ?? "")\n\n"
		rows?.forEach { md.append($0.markdown(indentLevel: 0)) }
		
		if returnToSuspend {
			suspend()
		}
		
		return md
	}
	
	public func opml() -> String {
		var returnToSuspend = false
		if rows == nil {
			returnToSuspend = true
			load()
		}

		var opml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
		opml.append("<!-- OPML generated by Zavala -->\n")
		opml.append("<opml version=\"2.0\">\n")
		opml.append("<head>\n")
		opml.append("  <title>\(title?.escapingSpecialXMLCharacters ?? "")</title>\n")
		if let dateCreated = created?.rfc822String {
			opml.append("  <dateCreated>\(dateCreated)</dateCreated>\n")
		}
		if let dateModified = updated?.rfc822String {
			opml.append("  <dateModified>\(dateModified)</dateModified>\n")
		}
		if let ownerName = ownerName {
			opml.append("  <ownerName>\(ownerName)</ownerName>\n")
		}
		if let ownerEmail = ownerEmail {
			opml.append("  <ownerEmail>\(ownerEmail)</ownerEmail>\n")
		}
		if let ownerURL = ownerURL {
			opml.append("  <ownerID>\(ownerURL)</ownerID>\n")
		}
		opml.append("  <expansionState>\(expansionState)</expansionState>\n")
		if let verticleScrollState = verticleScrollState {
			opml.append("  <vertScrollState>\(verticleScrollState)</vertScrollState>\n")
		}
		opml.append("</head>\n")
		opml.append("<body>\n")
		rows?.forEach { opml.append($0.opml()) }
		opml.append("</body>\n")
		opml.append("</opml>\n")

		if returnToSuspend {
			suspend()
		}

		return opml
	}
	
	public func toggleFavorite() {
		isFavorite = !(isFavorite ?? false)
		documentMetaDataDidChange()
	}
	
	public func toggleFilter() -> ShadowTableChanges {
		isFiltered = !(isFiltered ?? false)
		documentMetaDataDidChange()
		return rebuildShadowTable()
	}
	
	public func update(title: String) {
		self.title = title
		self.updated = Date()
		documentTitleDidChange()
	}
	
	public func createNote(headline: TextRow, textRowStrings: TextRowStrings) -> ShadowTableChanges {
		headline.textRowStrings = textRowStrings
		
		if headline.noteAttributedText == nil {
			headline.noteAttributedText = NSAttributedString()
		}
		
		outlineBodyDidChange()
		
		guard let shadowTableIndex = shadowTable?.firstIndex(of: headline) else { return ShadowTableChanges() }
		return ShadowTableChanges(reloads: [shadowTableIndex])
	}
	
	public func deleteNote(headline: TextRow, textRowStrings: TextRowStrings) -> ShadowTableChanges {
		headline.textRowStrings = textRowStrings
		headline.noteAttributedText = nil
		
		outlineBodyDidChange()
		
		guard let shadowTableIndex = shadowTable?.firstIndex(of: headline) else { return ShadowTableChanges() }
		return ShadowTableChanges(reloads: [shadowTableIndex])
	}
	
	public func deleteHeadline(headline: TextRow, textRowStrings: TextRowStrings? = nil) -> ShadowTableChanges {
		if let texts = textRowStrings {
			headline.textRowStrings = texts
		}
		headline.parent?.rows?.removeFirst(object: headline)
		
		outlineBodyDidChange()
		
		guard let headlineShadowTableIndex = headline.shadowTableIndex else { return ShadowTableChanges() }
		var deletes = [headlineShadowTableIndex]
		
		func deleteVisitor(_ visited: TextRow) {
			if let index = visited.shadowTableIndex {
				deletes.append(index)
			}
			if visited.isExpanded ?? true {
				visited.rows?.forEach { $0.visit(visitor: deleteVisitor) }
			}
		}

		if headline.isExpanded ?? true {
			headline.rows?.forEach { $0.visit(visitor: deleteVisitor(_:)) }
		}

		for index in deletes.reversed() {
			shadowTable?.remove(at: index)
		}
		
		resetShadowTableIndexes(startingAt: headlineShadowTableIndex)
		
		if headlineShadowTableIndex > 0 {
			return ShadowTableChanges(deletes: Set(deletes), reloads: [headlineShadowTableIndex - 1])
		} else {
			return ShadowTableChanges(deletes: Set(deletes))
		}
			
	}
	
	public func joinHeadline(topHeadline: TextRow, bottomHeadline: TextRow) -> ShadowTableChanges {
		guard let topText = topHeadline.topicAttributedText,
			  let topShadowTableIndex = topHeadline.shadowTableIndex,
			  let bottomText = bottomHeadline.topicAttributedText else { return ShadowTableChanges() }
		
		let mutableText = NSMutableAttributedString(attributedString: topText)
		mutableText.append(bottomText)
		topHeadline.topicAttributedText = mutableText
		
		var changes = deleteHeadline(headline: bottomHeadline)
		changes.append(ShadowTableChanges(reloads: Set([topShadowTableIndex])))
		return changes
	}
	
	public func createHeadline(headline: TextRow, beforeHeadline: TextRow, textRowStrings: TextRowStrings? = nil) -> ShadowTableChanges {
		if let texts = textRowStrings {
			beforeHeadline.textRowStrings = texts
		}

		guard let parent = beforeHeadline.parent,
			  let index = parent.rows?.firstIndex(of: beforeHeadline),
			  let shadowTableIndex = beforeHeadline.shadowTableIndex else {
			return ShadowTableChanges()
		}
		
		parent.rows?.insert(headline, at: index)
		headline.parent = parent
		
		outlineBodyDidChange()

		shadowTable?.insert(headline, at: shadowTableIndex)
		resetShadowTableIndexes(startingAt: shadowTableIndex)
		return ShadowTableChanges(inserts: [shadowTableIndex])
	}
	
	public func createHeadline(headline: TextRow, afterHeadline: TextRow? = nil, textRowStrings: TextRowStrings? = nil) -> ShadowTableChanges {
		if let texts = textRowStrings {
			afterHeadline?.textRowStrings = texts
		}

		if let parent = headline.parent, parent as? TextRow == afterHeadline {
			parent.rows?.insert(headline, at: 0)
		} else if let parent = headline.parent {
			var headlines = parent.rows ?? [TextRow]()
			let insertIndex = headlines.firstIndex(where: { $0 == afterHeadline}) ?? headlines.count - 1
			headlines.insert(headline, at: insertIndex + 1)
			parent.rows = headlines
		} else if afterHeadline?.isExpanded ?? true && !(afterHeadline?.rows?.isEmpty ?? true) {
			afterHeadline!.rows!.insert(headline, at: 0)
			headline.parent = afterHeadline
		} else if let parent = afterHeadline?.parent {
			var headlines = parent.rows ?? [TextRow]()
			let insertIndex = headlines.firstIndex(where: { $0 == afterHeadline}) ?? -1
			headlines.insert(headline, at: insertIndex + 1)
			headline.parent = afterHeadline?.parent
			parent.rows = headlines
		} else {
			var headlines = self.rows ?? [TextRow]()
			let insertIndex = headlines.firstIndex(where: { $0 == afterHeadline}) ?? -1
			headlines.insert(headline, at: insertIndex + 1)
			headline.parent = self
			self.rows = headlines
		}
		
		outlineBodyDidChange()

		var headlines = [headline]
		
		func insertVisitor(_ visited: TextRow) {
			headlines.append(visited)
			if visited.isExpanded ?? true {
				visited.rows?.forEach { $0.visit(visitor: insertVisitor) }
			}
		}

		if headline.isExpanded ?? true {
			headline.rows?.forEach { $0.visit(visitor: insertVisitor(_:)) }
		}
		
		let afterShadowTableIndex = afterHeadline?.shadowTableIndex ?? -1
		let headlineShadowTableIndex = afterShadowTableIndex + 1

		var inserts = Set<Int>()
		for i in 0..<headlines.count {
			let shadowTableIndex = headlineShadowTableIndex + i
			inserts.insert(shadowTableIndex)
			shadowTable?.insert(headlines[i], at: shadowTableIndex)
		}
		
		headline.shadowTableIndex = headlineShadowTableIndex
		resetShadowTableIndexes(startingAt: headlineShadowTableIndex)
		
		return ShadowTableChanges(inserts: inserts)
	}
	
	public func splitHeadline(newHeadline: TextRow, headline: TextRow, topic: NSAttributedString, cursorPosition: Int) -> ShadowTableChanges {
		let newTopicRange = NSRange(location: cursorPosition, length: topic.length - cursorPosition)
		let newTopicText = topic.attributedSubstring(from: newTopicRange)
		newHeadline.topicAttributedText = newTopicText
		
		let headlineRange = NSRange(location: 0, length: cursorPosition)
		let headlineText = topic.attributedSubstring(from: headlineRange)
		headline.topicAttributedText = headlineText

		var changes = createHeadline(headline: newHeadline, afterHeadline: headline)
		if let headlineShadowTableIndex = headline.shadowTableIndex {
			changes.append(ShadowTableChanges(reloads: Set([headlineShadowTableIndex])))
		}
		return changes
	}

	public func updateHeadline(headline: TextRow, textRowStrings: TextRowStrings) -> ShadowTableChanges {
		headline.textRowStrings = textRowStrings
		outlineBodyDidChange()
		guard let shadowTableIndex = headline.shadowTableIndex else { return ShadowTableChanges() }
		return ShadowTableChanges(reloads: [shadowTableIndex])
	}
	
	public func toggleDisclosure(headline: TextRow) -> ShadowTableChanges {
		let changes: ShadowTableChanges
		if headline.isExpanded ?? true {
			changes = collapseHeadline(headline: headline)
		} else {
			changes = expandHeadline(headline: headline)
		}

		outlineBodyDidChange()
		return changes
	}
	
	public func isExpandAllUnavailable(container: RowContainer) -> Bool {
		if let headline = container as? TextRow, headline.isExpandable {
			return false
		}

		var unavailable = true
		
		func expandedRowVisitor(_ visited: TextRow) {
			for headline in visited.rows ?? [TextRow]() {
				unavailable = !headline.isExpandable
				if !unavailable {
					break
				}
				headline.visit(visitor: expandedRowVisitor)
				if !unavailable {
					break
				}
			}
		}

		for headline in container.rows ?? [TextRow]() {
			unavailable = !headline.isExpandable
			if !unavailable {
				break
			}
			headline.visit(visitor: expandedRowVisitor)
			if !unavailable {
				break
			}
		}
		
		return unavailable
	}
	
	public func expandAll(container: RowContainer) -> ([TextRow], ShadowTableChanges) {
		var expanded = [TextRow]()
		
		if let headline = container as? TextRow, headline.isExpandable {
			headline.isExpanded = true
			expanded.append(headline)
		}
		
		func expandVisitor(_ visited: TextRow) {
			if visited.isExpandable {
				visited.isExpanded = true
				expanded.append(visited)
			}
			visited.rows?.forEach { $0.visit(visitor: expandVisitor) }
		}

		container.rows?.forEach { $0.visit(visitor: expandVisitor(_:)) }
		
		outlineBodyDidChange()

		var changes = rebuildShadowTable()
		
		let reloads = Set(expanded.compactMap { $0.shadowTableIndex })
		changes.append(ShadowTableChanges(reloads: reloads))
		
		return (expanded, changes)
	}

	public func expand(headlines: [TextRow]) -> ShadowTableChanges {
		expandCollapse(headlines: headlines, isExpanded: true)
	}
	
	public func isCollapseAllUnavailable(container: RowContainer) -> Bool {
		if let headline = container as? TextRow, headline.isCollapsable {
			return false
		}
		
		var unavailable = true
		
		func collapsedRowVisitor(_ visited: TextRow) {
			for headline in visited.rows ?? [TextRow]() {
				unavailable = !headline.isCollapsable
				if !unavailable {
					break
				}
				headline.visit(visitor: collapsedRowVisitor)
				if !unavailable {
					break
				}
			}
		}

		for headline in container.rows ?? [TextRow]() {
			unavailable = !headline.isCollapsable
			if !unavailable {
				break
			}
			headline.visit(visitor: collapsedRowVisitor)
			if !unavailable {
				break
			}
		}
		
		return unavailable
	}
	
	public func collapseAll(container: RowContainer) -> ([TextRow], ShadowTableChanges) {
		var collapsed = [TextRow]()
		
		if let headline = container as? TextRow, headline.isCollapsable {
			headline.isExpanded = false
			collapsed.append(headline)
		}
		
		func collapseVisitor(_ visited: TextRow) {
			if visited.isCollapsable {
				visited.isExpanded = false
				collapsed.append(visited)
			}
			visited.rows?.forEach { $0.visit(visitor: collapseVisitor) }
		}

		var reloads: [TextRow]
		if let headline = container as? TextRow {
			reloads = [headline]
		} else {
			reloads = [TextRow]()
		}
		
		container.rows?.forEach {
			reloads.append($0)
			$0.visit(visitor: collapseVisitor(_:))
		}
		
		outlineBodyDidChange()

		var changes = rebuildShadowTable()
	
		let reloadIndexes = Set(reloads.compactMap { $0.shadowTableIndex })
		changes.append(ShadowTableChanges(reloads: reloadIndexes))
		
		return (collapsed, changes)
	}

	public func collapse(headlines: [TextRow]) -> ShadowTableChanges {
		expandCollapse(headlines: headlines, isExpanded: false)
	}
	
	public func toggleComplete(headline: TextRow, textRowStrings: TextRowStrings) -> ShadowTableChanges {
		headline.textRowStrings = textRowStrings
		headline.isComplete = !(headline.isComplete ?? false)
		outlineBodyDidChange()
		
		if isFiltered ?? false {
			return rebuildShadowTable()
		}
		
		guard let shadowTableIndex = headline.shadowTableIndex else { return ShadowTableChanges() }
		var reloads = Set([shadowTableIndex])
		
		func reloadVisitor(_ visited: TextRow) {
			if let index = visited.shadowTableIndex {
				reloads.insert(index)
			}
			if visited.isExpanded ?? true {
				visited.rows?.forEach { $0.visit(visitor: reloadVisitor) }
			}
		}

		if headline.isExpanded ?? true {
			headline.rows?.forEach { $0.visit(visitor: reloadVisitor(_:)) }
		}
		
		return ShadowTableChanges(reloads: reloads)
	}

	public func isIndentHeadlineUnavailable(headline: TextRow) -> Bool {
		let container: RowContainer
		if let oldParentHeadline = headline.parent {
			container = oldParentHeadline
		} else {
			container = self
		}
		
		if let headlineIndex = container.rows?.firstIndex(of: headline), headlineIndex > 0 {
			return false
		}
		
		return true
	}
	
	public func indentHeadline(headline: TextRow, textRowStrings: TextRowStrings) -> ShadowTableChanges {
		headline.textRowStrings = textRowStrings
		
		guard let container = headline.parent,
			  let headlineIndex = container.rows?.firstIndex(of: headline),
			  headlineIndex > 0,
			  let newParentHeadline = container.rows?[headlineIndex - 1] else { return ShadowTableChanges() }

		var expandChange = expandHeadline(headline: newParentHeadline)
		
		// Null out the chevron row reload since we are going to add it below
		expandChange.reloads = nil
		
		guard let headlineShadowTableIndex = headline.shadowTableIndex,
			  let newParentHeadlineShadowTableIndex = newParentHeadline.shadowTableIndex else { return expandChange }

		var siblingHeadlines = newParentHeadline.rows ?? [TextRow]()
		headline.parent = newParentHeadline
		siblingHeadlines.append(headline)
		newParentHeadline.rows = siblingHeadlines
		container.rows?.removeFirst(object: headline)

		newParentHeadline.isExpanded = true
		outlineBodyDidChange()
		
		var reloads = Set<Int>()
		reloads.insert(newParentHeadlineShadowTableIndex)
		reloads.insert(headlineShadowTableIndex)

		func reloadVisitor(_ visited: TextRow) {
			if let index = visited.shadowTableIndex {
				reloads.insert(index)
			}
			if visited.isExpanded ?? true {
				visited.rows?.forEach { $0.visit(visitor: reloadVisitor) }
			}
		}

		if headline.isExpanded ?? true {
			headline.rows?.forEach { $0.visit(visitor: reloadVisitor(_:)) }
		}

		expandChange.append(ShadowTableChanges(reloads: reloads))
		return expandChange

	}
	
	public func isOutdentHeadlineUnavailable(headline: TextRow) -> Bool {
		return headline.indentLevel == 0
	}
		
	public func outdentHeadline(headline: TextRow, textRowStrings: TextRowStrings) -> ShadowTableChanges {
		headline.textRowStrings = textRowStrings

		guard let oldParent = headline.parent as? TextRow,
			  let oldParentHeadlines = oldParent.rows,
			  let oldParentShadowTableIndex = oldParent.shadowTableIndex,
			  let originalHeadlineShadowTableIndex = headline.shadowTableIndex else { return ShadowTableChanges() }
		
		guard let oldHeadlineIndex = oldParentHeadlines.firstIndex(of: headline) else { return ShadowTableChanges() }
		var siblingsToMove = [TextRow]()
		for i in (oldHeadlineIndex + 1)..<oldParentHeadlines.count {
			siblingsToMove.append(oldParentHeadlines[i])
		}

		oldParent.rows?.removeFirst(object: headline)

		if let newParent = oldParent.parent, let oldParentIndex = newParent.rows?.firstIndex(of: oldParent) {
			newParent.rows?.insert(headline, at: oldParentIndex + 1)
		} else {
			if let oldParentIndex = rows?.firstIndex(of: oldParent) {
				rows?.insert(headline, at: oldParentIndex + 1)
			}
		}
		headline.parent = oldParent.parent

		outlineBodyDidChange()

		var reloads = Set([oldParentShadowTableIndex])
		var moves = Set<ShadowTableChanges.Move>()
		var workingShadowTableIndex = originalHeadlineShadowTableIndex
		
		if siblingsToMove.isEmpty {
			reloads.insert(originalHeadlineShadowTableIndex)
			
			func reloadVisitor(_ visited: TextRow) {
				if let index = visited.shadowTableIndex {
					reloads.insert(index)
				}
				if visited.isExpanded ?? true {
					visited.rows?.forEach { $0.visit(visitor: reloadVisitor) }
				}
			}
			
			if headline.isExpanded ?? true {
				headline.rows?.forEach { $0.visit(visitor: reloadVisitor(_:)) }
			}
		} else {
			
			func shadowTableRemoveVisitor(_ visited: TextRow) {
				if visited.isExpanded ?? true {
					visited.rows?.reversed().forEach {	$0.visit(visitor: shadowTableRemoveVisitor)	}
				}
				if let visitedShadowTableIndex = visited.shadowTableIndex {
					shadowTable?.remove(at: visitedShadowTableIndex)
				}
			}

			if headline.isExpanded ?? true {
				headline.rows?.reversed().forEach { $0.visit(visitor: shadowTableRemoveVisitor(_:)) }
			}
			shadowTable?.remove(at: originalHeadlineShadowTableIndex)

			func movingUpVisitor(_ visited: TextRow) {
				if let visitedShadowTableIndex = visited.shadowTableIndex {
					moves.insert(ShadowTableChanges.Move(visitedShadowTableIndex, workingShadowTableIndex))
					workingShadowTableIndex = workingShadowTableIndex + 1
				}
				if visited.isExpanded ?? true {
					visited.rows?.forEach { $0.visit(visitor: movingUpVisitor)	}
				}
			}

			for sibling in siblingsToMove {
				if let siblineShadowTableIndex = sibling.shadowTableIndex {
					moves.insert(ShadowTableChanges.Move(siblineShadowTableIndex, workingShadowTableIndex))
					workingShadowTableIndex = workingShadowTableIndex + 1
					if sibling.isExpanded ?? true {
						sibling.rows?.forEach { $0.visit(visitor: movingUpVisitor(_:)) }
					}
				}
			}
			
			moves.insert(ShadowTableChanges.Move(originalHeadlineShadowTableIndex, workingShadowTableIndex))
			reloads.insert(workingShadowTableIndex)
			shadowTable?.insert(headline, at: workingShadowTableIndex)

			func shadowTableInsertVisitor(_ visited: TextRow) {
				if let visitedShadowTableIndex = visited.shadowTableIndex {
					workingShadowTableIndex = workingShadowTableIndex + 1
					shadowTable?.insert(visited, at: workingShadowTableIndex)
					moves.insert(ShadowTableChanges.Move(visitedShadowTableIndex, workingShadowTableIndex))
					reloads.insert(workingShadowTableIndex)
				}
				if visited.isExpanded ?? true {
					visited.rows?.forEach { $0.visit(visitor: shadowTableInsertVisitor) }
				}
			}

			if headline.isExpanded ?? true {
				headline.rows?.forEach { $0.visit(visitor: shadowTableInsertVisitor(_:)) }
			}
		}
		
		resetShadowTableIndexes(startingAt: originalHeadlineShadowTableIndex)
		return ShadowTableChanges(moves: moves, reloads: reloads)
	}
	
	public func moveHeadline(_ headline: TextRow, textRowStrings: TextRowStrings? = nil, toParent: RowContainer, childIndex: Int) -> ShadowTableChanges {
		if let texts = textRowStrings {
			headline.textRowStrings = texts
		}

		// Move the headline in the tree
		headline.parent?.rows?.removeFirst(object: headline)
		if toParent.rows == nil {
			toParent.rows = [headline]
		} else {
			toParent.rows!.insert(headline, at: childIndex)
		}

		outlineBodyDidChange()

		var changes = rebuildShadowTable()
		
		guard let shadowTableIndex = shadowTable?.firstIndex(of: headline) else {
			return changes
		}

		var reloads = [shadowTableIndex]
		if shadowTableIndex > 0 {
			reloads.append(shadowTableIndex - 1)
		}
		
		func reloadVisitor(_ visited: TextRow) {
			if let index = visited.shadowTableIndex {
				reloads.append(index)
			}
			if visited.isExpanded ?? true {
				visited.rows?.forEach { $0.visit(visitor: reloadVisitor) }
			}
		}

		if headline.isExpanded ?? true {
			headline.rows?.forEach { $0.visit(visitor: reloadVisitor(_:)) }
		}

		changes.append(ShadowTableChanges(reloads: Set(reloads)))
		return changes
	}
	
	public func load() {
		rowsFile = RowsFile(outline: self)
		rowsFile!.load()
		rebuildTransientData()
	}
	
	public func save() {
		rowsFile?.save()
	}
	
	public func forceSave() {
		if rowsFile == nil {
			rowsFile = RowsFile(outline: self)
		}
		rowsFile?.markAsDirty()
		rowsFile?.save()
	}
	
	public func delete() {
		if rowsFile == nil {
			rowsFile = RowsFile(outline: self)
		}
		rowsFile?.delete()
		rowsFile = nil
		outlineDidDelete()
	}
	
	public func suspend() {
		rowsFile?.save()
		rowsFile = nil
		rows = nil
		shadowTable = nil
		_idToRowDictionary = [String: TextRow]()
	}
	
	public static func == (lhs: Outline, rhs: Outline) -> Bool {
		return lhs.id == rhs.id
	}
	
}

// MARK: CustomDebugStringConvertible

extension Outline: CustomDebugStringConvertible {
	
	public var debugDescription: String {
		var output = ""
		for headline in rows ?? [TextRow]() {
			output.append(dumpHeadline(level: 0, headline: headline))
		}
		return output
	}
	
	private func dumpHeadline(level: Int, headline: TextRow) -> String {
		var output = ""
		for _ in 0..<level {
			output.append(" -- ")
		}
		output.append(headline.debugDescription)
		output.append("\n")
		
		for child in headline.rows ?? [TextRow]() {
			output.append(dumpHeadline(level: level + 1, headline: child))
		}
		
		return output
	}
	
}

// MARK: Helpers

extension Outline {
	
	private func documentTitleDidChange() {
		NotificationCenter.default.post(name: .DocumentTitleDidChange, object: Document.outline(self), userInfo: nil)
	}

	private func documentMetaDataDidChange() {
		NotificationCenter.default.post(name: .DocumentMetaDataDidChange, object: Document.outline(self), userInfo: nil)
	}

	private func outlineBodyDidChange() {
		self.updated = Date()
		documentMetaDataDidChange()
		rowDictionaryNeedUpdate = true
		rowsFile?.markAsDirty()
		NotificationCenter.default.post(name: .OutlineBodyDidChange, object: self, userInfo: nil)
	}
	
	private func outlineDidDelete() {
		NotificationCenter.default.post(name: .DocumentDidDelete, object: Document.outline(self), userInfo: nil)
	}

	private func expandCollapse(headlines: [TextRow], isExpanded: Bool) -> ShadowTableChanges {
		for headline in headlines {
			headline.isExpanded = isExpanded
		}
		
		outlineBodyDidChange()

		var changes = rebuildShadowTable()
		
		let reloads = Set(headlines.compactMap { $0.shadowTableIndex })
		changes.append(ShadowTableChanges(reloads: reloads))
		
		return changes
	}
	
	private func expandHeadline(headline: TextRow) -> ShadowTableChanges {
		guard !(headline.isExpanded ?? true), let headlineShadowTableIndex = headline.shadowTableIndex else {
			return ShadowTableChanges()
		}
		
		headline.isExpanded = true

		var shadowTableInserts = [TextRow]()

		func visitor(_ visited: TextRow) {
			let shouldFilter = isFiltered ?? false && visited.isComplete ?? false
			
			if !shouldFilter {
				shadowTableInserts.append(visited)

				if visited.isExpanded ?? true {
					visited.rows?.forEach {
						$0.visit(visitor: visitor)
					}
				}
			}
		}

		headline.rows?.forEach { headline in
			headline.visit(visitor: visitor(_:))
		}
		
		var inserts = Set<Int>()
		for i in 0..<shadowTableInserts.count {
			let newIndex = i + headlineShadowTableIndex + 1
			shadowTable?.insert(shadowTableInserts[i], at: newIndex)
			inserts.insert(newIndex)
		}
		
		resetShadowTableIndexes(startingAt: headlineShadowTableIndex)
		return ShadowTableChanges(inserts: inserts, reloads: [headlineShadowTableIndex])
	}
	
	private func collapseHeadline(headline: TextRow) -> ShadowTableChanges {
		guard headline.isExpanded ?? true else { return ShadowTableChanges() }

		headline.isExpanded = false
			
		var reloads = Set<Int>()

		func visitor(_ visited: TextRow) {
			if let shadowTableIndex = visited.shadowTableIndex {
				reloads.insert(shadowTableIndex)
			}

			if visited.isExpanded ?? true {
				visited.rows?.forEach {
					$0.visit(visitor: visitor)
				}
			}
		}
		
		headline.rows?.forEach { headline in
			headline.visit(visitor: visitor(_:))
		}
		
		shadowTable?.remove(atOffsets: IndexSet(reloads))
		
		guard let headlineShadowTableIndex = headline.shadowTableIndex else { return ShadowTableChanges() }
		resetShadowTableIndexes(startingAt: headlineShadowTableIndex)
		return ShadowTableChanges(deletes: reloads, reloads: Set([headlineShadowTableIndex]))
	}
	
	func rebuildHeadlineDictionary() {
		var idDictionary = [String: TextRow]()
		
		func dictBuildVisitor(_ visited: TextRow) {
			idDictionary[visited.id] = visited
			visited.rows?.forEach { $0.visit(visitor: dictBuildVisitor) }
		}

		rows?.forEach { $0.visit(visitor: dictBuildVisitor(_:)) }
		
		_idToRowDictionary = idDictionary
		rowDictionaryNeedUpdate = false
	}
	
	private func rebuildShadowTable() -> ShadowTableChanges {
		guard let oldShadowTable = shadowTable else { return ShadowTableChanges() }
		rebuildTransientData()
		
		var moves = Set<ShadowTableChanges.Move>()
		var inserts = Set<Int>()
		var deletes = Set<Int>()
		
		let diff = shadowTable!.difference(from: oldShadowTable).inferringMoves()
		for change in diff {
			switch change {
			case .insert(let offset, _, let associated):
				if let associated = associated {
					moves.insert(ShadowTableChanges.Move(associated, offset))
				} else {
					inserts.insert(offset)
				}
			case .remove(let offset, _, let associated):
				if let associated = associated {
					moves.insert(ShadowTableChanges.Move(offset, associated))
				} else {
					deletes.insert(offset)
				}
			}
		}
		
		return ShadowTableChanges(deletes: deletes, inserts: inserts, moves: moves)
	}
	
	private func rebuildTransientData() {
		let transient = TransientDataVisitor(isFiltered: isFiltered ?? false)
		rows?.forEach { headline in
			headline.parent = self
			headline.visit(visitor: transient.visitor(_:))
		}
		self.shadowTable = transient.shadowTable
	}
	
	private func resetShadowTableIndexes(startingAt: Int = 0) {
		guard let shadowTable = shadowTable else { return }
		for i in startingAt..<shadowTable.count {
			shadowTable[i].shadowTableIndex = i
		}
	}
	
}
